image_size: [1024, 1024]

dbnet:
  shrink: false
  max_distance: 32

classes:
  - text

train_data:
  src_path: data/val.txt
  lmdb_path: lmdb/train_data

val_data:
  src_path: data/val.txt
  lmdb_path: lmdb/val_lmdb
